psexec -d WeatherSyncToAsyncResult.bat
psexec -d WeatherSyncToAsyncResult.bat
psexec -d WeatherSyncToAsyncResult.bat
psexec -d WeatherSyncToAsyncResult.bat
psexec -d WeatherSyncToAsyncResult.bat
psexec -d WeatherSyncToAsyncResult.bat
psexec -d WeatherSyncToAsyncResult.bat
psexec -d WeatherSyncToAsyncResult.bat
psexec -d WeatherSyncToAsyncResult.bat
psexec -d WeatherSyncToAsyncResult.bat
