psexec -d Weather.bat
psexec -d Weather.bat
psexec -d Weather.bat
psexec -d Weather.bat
psexec -d Weather.bat
psexec -d Weather.bat
psexec -d Weather.bat
psexec -d Weather.bat
psexec -d Weather.bat
psexec -d Weather.bat